[package]
name = "rust-echo-server"
version = "0.1.0"

[dependencies]
clap = "*"
env_logger = "*"
log = "*"

[[bin]]
name = "coio-tcp-echo-server"

[dependencies.mioco]
git = "https://github.com/dpc/mioco.git"

[profile.release]
lto=true
